on:
  push:
    branches:
      - main

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v3
        id: release
        with:
          release-type: python
          package-name: conda-inject

      - uses: actions/checkout@v3
        if: ${{ steps.release.outputs.release_created }}

      - name: Install poetry
        if: ${{ steps.release.outputs.release_created }}
        run: pipx install poetry

      - name: Determine dependencies
        if: ${{ steps.release.outputs.release_created }}
        run: poetry lock

      - uses: actions/setup-python@v4
        if: ${{ steps.release.outputs.release_created }}
        with:
          python-version: "3.11"
          cache: poetry

      - name: Install Dependencies using Poetry
        if: ${{ steps.release.outputs.release_created }}
        run: poetry install

      - name: Publish to PyPi
        if: ${{ steps.release.outputs.release_created }}
        env:
          PYPI_USERNAME: __token__
          PYPI_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: poetry publish --build --username $PYPI_USERNAME --password $PYPI_PASSWORD
